//	Copyright (c) 2022 Arne Scheffler
//  This code is distributed under the terms of the GNU General Public License

//  MVerb is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  at your option) any later version.
//
//  MVerb is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this MVerb.  If not, see <http://www.gnu.org/licenses/>.

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"MVerb.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"MVerb VST3 (64Bit)"
#else
#define stringFileDescription	"MVerb VST3"
#endif
#define stringCompanyName		"\0"
#define stringLegalCopyright	"Copyright(c) 2022"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
